import type { NextConfig } from "next";
import { legacyRedirects } from "./lib/legacy-redirects";

const nextConfig: NextConfig = {
  images: {
    /* Every editor-uploaded image is served from Sanity's CDN. */
    remotePatterns: [{ protocol: "https", hostname: "cdn.sanity.io" }],
  },
  async redirects() {
    return [
      /* The pre-launch privacy stub lived at /privacy; the published
         documents use the same slugs as the sister site. */
      { source: "/privacy", destination: "/privacy-policy", permanent: true },
      /* URLs of the two earlier sites (WordPress, then Wix), generated by
         scripts/build-redirects.ts — see docs/REDIRECTS.md. */
      ...legacyRedirects.map((r) => ({ ...r, permanent: true })),
    ];
  },
};

export default nextConfig;
