/* GENERATED by scripts/build-redirects.ts — do not edit by hand.
   Re-run `pnpm redirects:build --apply` and review the diff.
   Every legacy URL and where it goes: docs/REDIRECTS.csv. */

export type LegacyRedirect = { source: string; destination: string };

export const legacyRedirects: LegacyRedirect[] = [
  {
    "source": "/about-1",
    "destination": "/about"
  },
  {
    "source": "/benefit-cosmetics",
    "destination": "/work"
  },
  {
    "source": "/case-studies",
    "destination": "/work"
  },
  {
    "source": "/click-live-program",
    "destination": "/talent-management"
  },
  {
    "source": "/coke-mcdonalds-gamerfeeds",
    "destination": "/work"
  },
  {
    "source": "/contact-us",
    "destination": "/contact"
  },
  {
    "source": "/creator-highlights",
    "destination": "/talent"
  },
  {
    "source": "/creator/aussieantics",
    "destination": "/talent/aussieantics"
  },
  {
    "source": "/creator/bundun",
    "destination": "/talent/bundun"
  },
  {
    "source": "/creator/eddievr",
    "destination": "/talent/eddievr"
  },
  {
    "source": "/creator/more-muselk",
    "destination": "/talent/muselk"
  },
  {
    "source": "/creator/muselk",
    "destination": "/talent/muselk"
  },
  {
    "source": "/creator/surfingwithnoz",
    "destination": "/talent/surfingwithnoz"
  },
  {
    "source": "/creator/the-boys",
    "destination": "/talent/the-boys"
  },
  {
    "source": "/creator/the-boys-gaming",
    "destination": "/talent/the-boys"
  },
  {
    "source": "/maybelline-through-their-eyes",
    "destination": "/work"
  },
  {
    "source": "/multiversus",
    "destination": "/work"
  },
  {
    "source": "/our-creators-demo",
    "destination": "/talent"
  },
  {
    "source": "/our-creators-demo1",
    "destination": "/talent"
  },
  {
    "source": "/our-creators/aussieantics",
    "destination": "/talent/aussieantics"
  },
  {
    "source": "/our-creators/aussieantics-new-format",
    "destination": "/talent/aussieantics"
  },
  {
    "source": "/our-creators/bundun",
    "destination": "/talent/bundun"
  },
  {
    "source": "/our-creators/bundun-new-format",
    "destination": "/talent/bundun"
  },
  {
    "source": "/our-creators/eddievr",
    "destination": "/talent/eddievr"
  },
  {
    "source": "/our-creators/eddievr-new-format",
    "destination": "/talent/eddievr"
  },
  {
    "source": "/our-creators/more-muselk",
    "destination": "/talent/muselk"
  },
  {
    "source": "/our-creators/moremuselk-new-format",
    "destination": "/talent/muselk"
  },
  {
    "source": "/our-creators/muselk",
    "destination": "/talent/muselk"
  },
  {
    "source": "/our-creators/muselk-new-format",
    "destination": "/talent/muselk"
  },
  {
    "source": "/our-creators/surfingwithnoz",
    "destination": "/talent/surfingwithnoz"
  },
  {
    "source": "/our-creators/the-boys",
    "destination": "/talent/the-boys"
  },
  {
    "source": "/our-creators/theboys-new-format",
    "destination": "/talent/the-boys"
  },
  {
    "source": "/our-creators/theboysgaming-new-format",
    "destination": "/talent/the-boys"
  },
  {
    "source": "/our-maps",
    "destination": "/"
  },
  {
    "source": "/our-work",
    "destination": "/work"
  },
  {
    "source": "/services",
    "destination": "/"
  },
  {
    "source": "/talentprofiles/aussieantics",
    "destination": "/talent/aussieantics"
  },
  {
    "source": "/talentprofiles/bundun",
    "destination": "/talent/bundun"
  },
  {
    "source": "/talentprofiles/eddievr",
    "destination": "/talent/eddievr"
  },
  {
    "source": "/talentprofiles/moremuselk",
    "destination": "/talent/muselk"
  },
  {
    "source": "/talentprofiles/muselk",
    "destination": "/talent/muselk"
  },
  {
    "source": "/talentprofiles/surfingwithnoz",
    "destination": "/talent/surfingwithnoz"
  },
  {
    "source": "/talentprofiles/theboys",
    "destination": "/talent/the-boys"
  },
  {
    "source": "/talentprofiles/theboysgaming",
    "destination": "/talent/the-boys"
  },
  {
    "source": "/terms-conditions",
    "destination": "/terms-of-use"
  },
  {
    "source": "/thank-you",
    "destination": "/contact"
  },
  {
    "source": "/youtube-game-on",
    "destination": "/work"
  },
  {
    "source": "/youtube-shorts",
    "destination": "/work"
  },
  {
    "source": "/talentprofiles/:path*",
    "destination": "/talent"
  },
  {
    "source": "/our-creators/:path*",
    "destination": "/talent"
  },
  {
    "source": "/creator/:path*",
    "destination": "/talent"
  },
  {
    "source": "/creators/:path*",
    "destination": "/talent"
  },
  {
    "source": "/genre/:path*",
    "destination": "/talent"
  },
  {
    "source": "/primary-platform/:path*",
    "destination": "/talent"
  },
  {
    "source": "/primary-content/:path*",
    "destination": "/talent"
  },
  {
    "source": "/primary-deliverable/:path*",
    "destination": "/talent"
  },
  {
    "source": "/contents/:path*",
    "destination": "/talent"
  }
];

/** First path segments a CMS page must not use. */
export const reservedSlugs: string[] = [
  "about-1",
  "benefit-cosmetics",
  "case-studies",
  "click-live-program",
  "coke-mcdonalds-gamerfeeds",
  "contact-us",
  "contents",
  "creator",
  "creator-highlights",
  "creators",
  "genre",
  "maybelline-through-their-eyes",
  "multiversus",
  "our-creators",
  "our-creators-demo",
  "our-creators-demo1",
  "our-maps",
  "our-work",
  "primary-content",
  "primary-deliverable",
  "primary-platform",
  "services",
  "talentprofiles",
  "terms-conditions",
  "thank-you",
  "youtube-game-on",
  "youtube-shorts"
];
