import { createClient } from "next-sanity";
import { apiVersion, dataset, projectId } from "@/sanity/env";

/* Server-only read client.

   Production reads published documents from Sanity's CDN — the right
   default for a static site whose pages are regenerated by webhook.

   Anywhere else, if SANITY_API_READ_TOKEN is set, it reads drafts too:
   placeholder creators are kept as drafts so they can never reach the
   live site, yet the layouts stay reviewable populated on localhost and
   on Vercel preview deployments (set the token there, never on
   Production). This is the successor to the old SHOW_PLACEHOLDERS switch. */
const token = process.env.SANITY_API_READ_TOKEN;
const previewDrafts = process.env.VERCEL_ENV !== "production" && !!token;

export const client = createClient({
  projectId,
  dataset,
  apiVersion,
  useCdn: !previewDrafts,
  token: previewDrafts ? token : undefined,
  perspective: previewDrafts ? "drafts" : "published",
});
